export const ADD_FAV_REQUEST = 'ADD_FAV_REQUEST';
export const ADD_FAV_SUCCESS = 'ADD_FAV_SUCCESS';
export const ADD_FAV_FAILURE = 'ADD_FAV_FAILURE';

export const REMOVE_FAV_REQUEST = 'REMOVE_FAV_REQUEST';
export const REMOVE_FAV_SUCCESS = 'REMOVE_FAV_SUCCESS';
export const REMOVE_FAV_FAILURE = 'REMOVE_FAV_FAILURE';

export const ADD_CART_REQUEST = 'ADD_CART_REQUEST';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_FAILURE = 'ADD_CART_FAILURE';

export const REMOVE_CART_REQUEST = 'REMOVE_CART_REQUEST';
export const REMOVE_CART_SUCCESS = 'REMOVE_CART_SUCCESS';
export const REMOVE_CART_FAILURE = 'REMOVE_CART_FAILURE';

export const USER_CART_LOADING = 'USER_CART_LOADING';
export const USER_CART_LOADING_REQUEST = 'USER_CART_LOADING_REQUEST';
